const body=document.body, nav=document.querySelector('.nav'), menu=document.querySelector('.menu'), mobile=document.querySelector('.mobile-nav');
window.addEventListener('scroll',()=>{nav?.classList.toggle('scrolled',scrollY>30);const h=document.documentElement.scrollHeight-innerHeight;document.querySelector('.scroll-line span').style.height=(h?scrollY/h*100:0)+'%';},{passive:true});
menu?.addEventListener('click',()=>{const open=mobile.classList.toggle('open');body.classList.toggle('lock',open);menu.setAttribute('aria-expanded',String(open));mobile.setAttribute('aria-hidden',String(!open));});
mobile?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobile.classList.remove('open');body.classList.remove('lock');menu.setAttribute('aria-expanded','false');mobile.setAttribute('aria-hidden','true')}));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
const filters=[...document.querySelectorAll('.filter button')], items=[...document.querySelectorAll('.archive-item')];
filters.forEach(b=>b.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;items.forEach(i=>i.classList.toggle('is-hidden',f!=='all'&&i.dataset.category!==f));}));
const lb=document.querySelector('.lightbox'), lbImg=lb.querySelector('img'), lbCap=lb.querySelector('figcaption');let current=0;
function visible(){return items.filter(i=>!i.classList.contains('is-hidden'))}function setLb(i){const list=visible(),item=list[i];if(!item)return;current=i;lbImg.src=item.dataset.full;lbImg.alt=item.querySelector('img').alt;lbCap.textContent=item.querySelector('span').textContent}
items.forEach(item=>item.addEventListener('click',()=>{const list=visible();setLb(list.indexOf(item));lb.classList.add('open');lb.setAttribute('aria-hidden','false');body.classList.add('lock')}));
function closeLb(){lb.classList.remove('open');lb.setAttribute('aria-hidden','true');body.classList.remove('lock');setTimeout(()=>lbImg.src='',250)}
function step(d){const list=visible();if(!list.length)return;setLb((current+d+list.length)%list.length)}
lb.querySelector('.lb-close').addEventListener('click',closeLb);lb.querySelector('.lb-prev').addEventListener('click',()=>step(-1));lb.querySelector('.lb-next').addEventListener('click',()=>step(1));lb.addEventListener('click',e=>{if(e.target===lb)closeLb()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLb();if(lb.classList.contains('open')&&e.key==='ArrowLeft')step(-1);if(lb.classList.contains('open')&&e.key==='ArrowRight')step(1)});
const cursor=document.querySelector('.cursor');if(cursor&&matchMedia('(pointer:fine)').matches){addEventListener('pointermove',e=>cursor.style.left=e.clientX+'px', {passive:true});addEventListener('pointermove',e=>cursor.style.top=e.clientY+'px',{passive:true});document.querySelectorAll('a,button,video').forEach(el=>{el.addEventListener('mouseenter',()=>cursor.classList.add('active'));el.addEventListener('mouseleave',()=>cursor.classList.remove('active'))})}
const vids=[...document.querySelectorAll('video')];const vo=new IntersectionObserver(es=>es.forEach(e=>{const v=e.target;if(e.isIntersecting&&e.intersectionRatio>.25){v.play().catch(()=>{})}else if(!v.controls)v.pause()}),{threshold:[0,.25,.6]});vids.forEach(v=>vo.observe(v));
document.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>img.closest('.archive-item,.feature-main,.feature-side,.about-photo,.full-image,.cta-bg')?.classList.add('media-error')));
